### ISSUE TITLE
Auto-start?

### ISSUE THREAD

**Issue by clumba** [3xz/auto-steam-queue#1]
Hi!

I remember first version of this script was started automatically, when i'm open explore page. Now it seems script has to be started manually. Can you add option for auto-start like it was before?

**Comment by calebleung** [comment]
Hey there,

So the idea is that as there is currently no sale going on, the script won't auto-start. You are still able to control how many queues to go through in the [/explore](http://store.steampowered.com/explore/) page. 

As this is by design, I won't be changing it. However, you can have it auto start by adding a `generateAndCompleteQueue(0, 3);` to your own copy/fork of the script at line 138, or somewhere outside of that if block in that function. 

Cheers!

**Comment by clumba** [comment]
> So the idea is that as there is currently no sale going on, the script won't auto-start.

Will you change that during next sale (winter, for example)? If there will be same steam explorer quest of course.

**Comment by calebleung** [comment]
Yes, that's the plan :)
